language: java
sudo: required
dist: trusty
group: edge

addons:
  apt:
    packages:
    - oracle-java9-installer
  sonarcloud:
    organization: "trellis-ldp"
    token:
      secure: "If8UpcEJdUuX/OPveC8IrCwWItbYZOKhvqmFrfm32xunRFGIGMeYiwEDOrJ2i0I0EhW9OiZvvfuWWEH/2nFUkHP6prqzgw92NCA0OGx2+TP22k4Sf+FvQ9DLy+A1Mx+aHg/AMwBQTa3bFSTbBNmbiOmBt+ObfEfbTIwuG2YVC0aABkAbtrDZ4oImF3p6WSdBpxoplJvMyA5epRJNk4NFlFd2j8MtvEImWnBAwD2gYlqZnKBX4HfPdcPfZdvuE3k24QObj8ccTzcciF7UZBMs57cCKBCm6LDF8CHNHbKj0mCS5J+1L512ma0tsZVoFEqf1qZ0gWBUBFJJFbaWbhop3OQl8hli54P+M32RXGjXnAbjkI9AtjlFsBD+SJ5AXuszr0rvD9ReawJBYKxew3Ox5qyuHN4T0mzf8Aw2kfbcFz+8xcGP7N8l6C7F+KJFMkADtrG3fDmZmXP5g6j4aEaqAUI0ncxBABJ+pqRIh2o270Wl68zK1sLSaghc3zjmcYTx3S5CTSnP33TUXPzPX4sK9dWDrMYvOr7XkXTjezU+W4oTp0xxiuxfWXN9E0OBlMXOUsbHSMhV5pOj9rTYZgXyb5YwpVTn9ezDLK1yLgjhZCV/OA4eD2VZGlmhS2zRbtmtA9aCo8uZWvTi1psTdInmOXIjEzaHl1tzuarodNwBySU="

jdk:
  - oraclejdk8
  - oraclejdk9

after_success:
  - ./gradlew jacocoTestReport coveralls sonarqube
